# Generated by Django 6.0.1 on 2026-02-06 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contacts_created_994491_idx'), models.Index(fields=['email'], name='contacts_email_2eb381_idx'), models.Index(fields=['is_read', 'is_archived'], name='contacts_is_read_85f7de_idx')],
            },
        ),
    ]
