# Generated by Django 6.0.1 on 2026-02-20 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_type', models.CharField(choices=[('company', 'Company'), ('owner-operator', 'Owner Operator')], db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('owner_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('company_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('motor_carrier_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('authority_age', models.IntegerField(blank=True, null=True)),
                ('number_of_trucks', models.CharField(max_length=50)),
                ('truck_type', models.CharField(max_length=100)),
                ('operation_area', models.CharField(max_length=100)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('communication_method', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signup Registration',
                'verbose_name_plural': 'Signup Registrations',
                'db_table': 'signups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='signups_created_87886d_idx'), models.Index(fields=['signup_type'], name='signups_signup__085705_idx'), models.Index(fields=['email'], name='signups_email_426ff4_idx'), models.Index(fields=['company_email'], name='signups_company_0f60ef_idx'), models.Index(fields=['owner_email'], name='signups_owner_e_90292a_idx'), models.Index(fields=['is_approved', 'is_active'], name='signups_is_appr_1eccf2_idx')],
            },
        ),
    ]
