# Generated by Django 6.0.1 on 2026-02-20 18:37

import uuid
from django.db import migrations, models


def migrate_to_uuid(apps, schema_editor):
    """Migrate signup IDs from bigint to UUID"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Add new UUID column
        cursor.execute("ALTER TABLE signups ADD COLUMN id_new UUID;")
        
        # Step 2: Generate UUIDs for all existing records
        cursor.execute("SELECT id FROM signups")
        old_ids = cursor.fetchall()
        
        for (old_id,) in old_ids:
            new_uuid = uuid.uuid4()
            cursor.execute(
                "UPDATE signups SET id_new = %s WHERE id = %s",
                [str(new_uuid), old_id]
            )
        
        # Step 3: Drop the primary key constraint
        try:
            cursor.execute("ALTER TABLE signups DROP CONSTRAINT signups_pkey;")
        except Exception:
            # Constraint might not exist or have different name
            pass
        
        # Step 4: Drop the old id column
        cursor.execute("ALTER TABLE signups DROP COLUMN id;")
        
        # Step 5: Rename id_new to id
        cursor.execute("ALTER TABLE signups RENAME COLUMN id_new TO id;")
        
        # Step 6: Make id NOT NULL and set as primary key
        cursor.execute("ALTER TABLE signups ALTER COLUMN id SET NOT NULL;")
        cursor.execute("ALTER TABLE signups ADD PRIMARY KEY (id);")


def reverse_migrate(apps, schema_editor):
    """Reverse migration - convert UUID back to bigint (not recommended)"""
    # This is complex and not recommended, but required for migration reversibility
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_signup'),
    ]

    operations = [
        migrations.RunPython(
            migrate_to_uuid,
            reverse_migrate,
        ),
        # Update the model state to reflect UUID field
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Unique identifier for the signup',
                primary_key=True,
                serialize=False
            ),
        ),
    ]
