# Generated by Django 6.0.1 on 2026-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_change_signup_id_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
    ]
