# Generated by Django 6.0.1 on 2026-02-20 18:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_remove_signup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the claim', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('preferred_route', models.CharField(max_length=255)),
                ('age_of_mc_authority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Claim Submission',
                'verbose_name_plural': 'Claim Submissions',
                'db_table': 'claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='claims_created_19cf88_idx'), models.Index(fields=['email'], name='claims_email_0da5e3_idx'), models.Index(fields=['company_name'], name='claims_company_83bb8a_idx'), models.Index(fields=['is_read', 'is_archived'], name='claims_is_read_209dcc_idx')],
            },
        ),
    ]
