# Generated by Django 6.0.1 on 2026-03-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='preferred_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
