# Generated by Django 6.0.1 on 2026-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_make_claim_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='operation_area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
