# Generated by Django 6.0.1 on 2026-03-04 15:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_simplify_signup_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the career application', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('city_state', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('position_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-Site')], help_text='Type of position: Remote or On-Site', max_length=20)),
                ('job_title', models.CharField(default='Truck Dispatching Sales Executive', help_text='Job title being applied for', max_length=255)),
                ('cover_note', models.TextField(blank=True, help_text='Cover letter or brief note from applicant', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interviewing', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for HR team', null=True)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'db_table': 'career_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='career_appl_created_dae7e2_idx'), models.Index(fields=['email'], name='career_appl_email_a60ac7_idx'), models.Index(fields=['position_type'], name='career_appl_positio_fe999e_idx'), models.Index(fields=['status'], name='career_appl_status_bd587b_idx'), models.Index(fields=['is_read', 'is_archived'], name='career_appl_is_read_899764_idx'), models.Index(fields=['status', 'position_type'], name='career_appl_status_589fc9_idx')],
            },
        ),
    ]
