/**
 * Case Studies Configuration
 * Real driver success stories for Grow Trucking 
 */

export interface CaseStudy {
  id: string
  slug: string
  driverName: string
  equipmentType: string
  equipmentBadge: string
  revenueIncrease: string
  revenueIncreaseValue: number // for sorting
  rpmBefore: string
  rpmAfter: string
  freightLane: string
  region: string
  outcome: 'Revenue Increase' | 'Fuel Savings' | 'Home Time'
  summary: string
  featured?: boolean
  // Full case study details
  challenge: string
  solution: string
  routeOptimization: string
  metrics: {
    label: string
    before: string
    after: string
  }[]
}

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    slug: 'marcus-thompson',
    driverName: 'Marcus Thompson',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van',
    revenueIncrease: '+$3,555/week',
    revenueIncreaseValue: 3555,
    rpmBefore: '$2.00',
    rpmAfter: '$2.65',
    freightLane: 'Produce / Auto Parts',
    region: 'Midwest',
    outcome: 'Revenue Increase',
    summary: 'Route optimization cut empty miles by 40%',
    featured: true,
    challenge: 'Marcus had been hauling dry van freight for 6 years but was earning just $2.00/mile due to poor load board choices. He was running mostly LTL freight with long wait times at docks, spending up to 4 hours daily on load searching, and routinely returning empty from Atlanta — losing hundreds of dollars per trip.',
    solution: 'Grow Trucking dispatchers audited Marcus\'s lane history and identified a consistent demand for temperature-sensitive produce running Chicago to Atlanta with a backhaul opportunity in auto parts. We negotiated a dedicated lane at $2.65/mile, coordinated with two produce brokers for guaranteed loads, and mapped dock appointment windows to eliminate detention.',
    routeOptimization: 'I-65 South via Indianapolis, cutting 38 miles vs. the I-57 route Marcus used before. Fuel stop optimization saved an additional $44 per trip.',
    metrics: [
      { label: 'Rate per Mile', before: '$2.00/mile', after: '$2.65/mile' },
      { label: 'Weekly Revenue', before: '$1,820', after: '$5,375' },
      { label: 'Empty Miles', before: '340 miles/week', after: '48 miles/week' },
      { label: 'Waiting Hours', before: '4+ hours daily', after: 'Under 30 min' },
    ],
  },
  {
    id: '2',
    slug: 'rosa-delgado',
    driverName: 'Rosa Delgado',
    equipmentType: 'Flatbed',
    equipmentBadge: '48\' Flatbed (OD Permitted)',
    revenueIncrease: '+$2,330/week',
    revenueIncreaseValue: 2330,
    rpmBefore: '$1.95',
    rpmAfter: '$2.80',
    freightLane: 'Oversize Machinery / Wind Energy',
    region: 'West Coast',
    outcome: 'Revenue Increase',
    summary: 'Oversize machinery loads optimized for maximum revenue',
    featured: true,
    challenge: 'Rosa was an owner-operator running a flatbed who had been stuck with construction materials at low spot rates. With fuel costs rising, she was barely breaking even on the Dallas-LA lane. She came to Grow Trucking after three consecutive months of net losses and was considering selling her truck.',
    solution: 'We identified that Rosa\'s flatbed was ideal for oversize machinery and wind turbine components — a high-demand, high-rate niche she had never tapped. Grow Trucking connected her with two industrial manufacturers and an energy company running regular OD loads. We handled all permitting paperwork, pilot car coordination, and state weight limit filings.',
    routeOptimization: 'I-20 West with a permitted OD corridor through New Mexico. We arranged fuel discounts at 7 Flying J locations along the route, reducing fuel cost by $0.09/gallon.',
    metrics: [
      { label: 'Rate per Mile', before: '$1.95/mile', after: '$2.80/mile' },
      { label: 'Weekly Net Income', before: '-$105 (loss)', after: '+$2,225 profit' },
      { label: 'Fuel Cost/Trip', before: '$980', after: '$740' },
      { label: 'Loads per Week', before: '6 loads', after: '9 loads' },
    ],
  },
  {
    id: '3',
    slug: 'derek-okafor',
    driverName: 'Derek Okafor',
    equipmentType: 'Reefer',
    equipmentBadge: '53\' Refrigerated Trailer',
    revenueIncrease: '+$2,700/week',
    revenueIncreaseValue: 2700,
    rpmBefore: '$2.05',
    rpmAfter: '$2.75',
    freightLane: 'Produce / Pharmaceutical / Seafood',
    region: 'Northeast',
    outcome: 'Revenue Increase',
    summary: 'Pharma and seafood loads consistently matched',
    featured: true,
    challenge: 'Derek ran reefer loads up and down the I-95 corridor but had no consistent broker relationships. He was forced to check multiple load boards hourly, often accepting loads out of desperation at rates well below market. His fuel surcharge was never properly calculated, costing him thousands per year.',
    solution: 'Grow Trucking built Derek a dedicated broker network with 4 vetted produce and pharmaceutical shippers on the NY-Miami lane. We implemented a dynamic fuel surcharge formula tied to the DOE weekly diesel index. Additionally, our dispatchers negotiated a standing rate agreement with a Miami-based seafood exporter for weekly northbound loads.',
    routeOptimization: 'Optimized I-95 corridor with pre-cleared weigh station passes via PrePass and scheduled rest stops aligned with ELD clock management, recovering 45 minutes of drive time per trip.',
    metrics: [
      { label: 'Broker Relationships', before: 'None (spot board)', after: '4 dedicated shippers' },
      { label: 'Average Rate', before: '$1,850/trip', after: '$2,500/trip' },
      { label: 'Fuel Surcharge Recovery', before: '$0/year', after: '$4,800/year' },
      { label: 'Weekly Hours Searching', before: '14 hours', after: '1 hour' },
    ],
  },
  {
    id: '4',
    slug: 'linda-pearson',
    driverName: 'Linda Pearson',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van (Solo)',
    revenueIncrease: '+$1,650/week',
    revenueIncreaseValue: 1650,
    rpmBefore: '$2.10',
    rpmAfter: '$2.60',
    freightLane: 'Tech Equipment / Aerospace Components',
    region: 'West Coast',
    outcome: 'Revenue Increase',
    summary: 'Solo driver transition optimized for premium tech freight',
    challenge: 'Linda had been team-driving with her husband but recently became a solo driver. Her revenue dropped 40% as her previous team arrangement had been optimized for HOS split-sleeper strategies that no longer applied. She was frustrated and felt invisible to good brokers who seemed to prefer fleets.',
    solution: 'Grow Trucking redesigned Linda\'s HOS strategy for solo operation — targeting shorter 550-650 mile days with premium regional shippers in tech equipment and aerospace components out of the Seattle metro. We also registered her authority with 3 freight marketplaces where our team vouched for her safety rating, immediately elevating her broker access.',
    routeOptimization: 'I-90 East through Spokane and I-84 South to Boise, then US-30 to Denver. This route avoided mountain grades near Snoqualmie Pass in winter, reducing tire wear cost by an estimated $800/year.',
    metrics: [
      { label: 'Revenue vs. Team Era', before: '-40% ($3,200/wk)', after: '-8% ($4,850/wk)' },
      { label: 'Broker Tier Access', before: 'Entry level only', after: 'Preferred carrier status' },
      { label: 'Load Type', before: 'General commodity', after: 'Tech/Aerospace (premium)' },
      { label: 'Days Home/Month', before: '2–3 days', after: '6–7 days' },
    ],
  },
  {
    id: '5',
    slug: 'james-kowalski',
    driverName: 'James "Big Jim" Kowalski',
    equipmentType: 'Dry Van',
    equipmentBadge: 'Peterbilt 389 — 53\' Dry Van',
    revenueIncrease: '$9,200/week',
    revenueIncreaseValue: 9200,
    rpmBefore: '$1.90',
    rpmAfter: '$2.90',
    freightLane: 'Automotive Parts / Manufacturing',
    region: 'Midwest',
    outcome: 'Revenue Increase',
    summary: 'New authority veteran driver fast-tracked to premium rates',
    challenge: 'Big Jim was a 22-year veteran who drove for a carrier that went under. Starting fresh as an owner-operator at 54, he had no broker relationships, no load history under his new authority, and was being offered entry-level rates despite decades of experience. He had just financed a new Peterbilt and needed $7,000/week to cover payments.',
    solution: 'We leveraged Jim\'s clean MVR and safety record to fast-track him into automotive parts lanes between Detroit and the Gulf Coast — an industry he was deeply familiar with. Grow Trucking personally called three automotive logistics managers and introduced Jim, providing his full safety record and references. Within 72 hours he had his first dedicated contract.',
    routeOptimization: 'I-75 South to I-24 West to I-65 South, avoiding the I-57 corridor where weigh stations have caused significant delays for oversized automotive shipments. Saved average of 55 minutes per southbound trip.',
    metrics: [
      { label: 'Weeks to First Contract', before: 'Had no contacts', after: '3 days with Grow Trucking' },
      { label: 'Weekly Gross Revenue', before: '$0 (starting out)', after: '$9,200/week' },
      { label: 'Truck Payment Coverage', before: 'Needed $7,000', after: '$9,200 — fully covered' },
      { label: 'Rate per Mile', before: '$1.90/mile', after: '$2.90/mile' },
      { label: 'Rate Compared to Peers', before: 'Entry-level rates', after: 'Veteran premium rates' },
    ],
  },
  {
    id: '6',
    slug: 'aisha-williams',
    driverName: 'Aisha Williams',
    equipmentType: 'Box Truck',
    equipmentBadge: '26\' Box Truck',
    revenueIncrease: '+$1,200/week',
    revenueIncreaseValue: 1200,
    rpmBefore: '$2.00',
    rpmAfter: '$2.52',
    freightLane: 'E-Commerce Fulfillment / Linehaul',
    region: 'Midwest',
    outcome: 'Revenue Increase',
    summary: 'Box truck transitioned from per-stop delivery to OTR linehaul',
    challenge: 'Aisha had a box truck and was running delivery contracts that paid per stop — an exhausting model that left her earning $14/hour after expenses despite working 70-hour weeks. She wanted to transition to OTR freight but had no idea how to start and was worried about insurance costs eating her margins.',
    solution: 'Grow Trucking helped Aisha convert to linehaul freight contracts with two regional e-commerce fulfillment centers. We negotiated a linehaul rate, helped her transition insurance from commercial delivery to OTR cargo coverage saving $180/month, and onboarded her with a lumper service so she wasn\'t unloading freight herself.',
    routeOptimization: 'I-55 North to I-57 to I-70 West. Grow Trucking identified a preferred weigh station bypass for her weight class and arranged a fuel card with a 12-cent per gallon discount at Love\'s and Pilot locations on the route.',
    metrics: [
      { label: 'Effective Hourly Rate', before: '$14/hour', after: '$38/hour' },
      { label: 'Weekly Hours Worked', before: '70 hours', after: '50 hours' },
      { label: 'Insurance Cost', before: '$1,240/month', after: '$1,060/month' },
      { label: 'Physical Load/Unload', before: 'Every delivery', after: 'Zero (lumper service)' },
    ],
  },
  {
    id: '7',
    slug: 'carlos-rivera',
    driverName: 'Carlos Rivera',
    equipmentType: 'Hazmat',
    equipmentBadge: 'Hazmat-Certified Dry Van',
    revenueIncrease: '+$596/week',
    revenueIncreaseValue: 596,
    rpmBefore: '$2.05',
    rpmAfter: '$2.70',
    freightLane: 'Chemical / Industrial Hazmat',
    region: 'West Coast',
    outcome: 'Revenue Increase',
    summary: 'Hazmat premium rates recovered and CSA violations cleared',
    challenge: 'Carlos ran hazmat loads but had been accepting rates as if he were hauling standard freight. He didn\'t know his hazmat endorsement commanded a premium, and his broker had been pocketing the difference. He also had two CSA violations from routing errors that were dragging down his safety score and limiting his access to quality shippers.',
    solution: 'Grow Trucking identified the hazmat premium opportunity immediately and re-engaged with chemical and industrial shippers who specifically need hazmat-endorsed drivers. Our compliance team helped Carlos file a DataQ challenge on one erroneous CSA violation, which was successfully removed. We also implemented a pre-trip route briefing system to avoid future violations.',
    routeOptimization: 'I-10 West to I-15 North. We flagged three historically problematic inspection sites on I-15 and provided Carlos with updated HOS documentation protocols that reduced his inspection time from 45 minutes to under 10 minutes at those locations.',
    metrics: [
      { label: 'Rate Premium (Hazmat)', before: 'None claimed ($2.05/mi)', after: '+$0.65/mi ($2.70/mi)' },
      { label: 'CSA Score', before: '68 (restricted access)', after: '41 (preferred access)' },
      { label: 'Inspection Duration', before: '45 min average', after: 'Under 10 min' },
      { label: 'Weekly Revenue Increase', before: 'Baseline', after: '+$596/week' },
    ],
  },
  {
    id: '8',
    slug: 'tommy-nguyen',
    driverName: 'Tommy Nguyen',
    equipmentType: 'Flatbed',
    equipmentBadge: '53\' Flatbed',
    revenueIncrease: '+$750/week',
    revenueIncreaseValue: 750,
    rpmBefore: '$1.95',
    rpmAfter: '$2.50',
    freightLane: 'Lumber / Building Materials',
    region: 'West Coast',
    outcome: 'Home Time',
    summary: 'Dispatch workload eliminated, reclaiming evenings and family time',
    challenge: 'Tommy had been dispatching himself and spending 3-4 hours every night planning routes, calling brokers, and managing paperwork. The mental exhaustion was affecting his driving performance, and he\'d had two near-miss incidents he attributed to fatigue from the combined workload. His wife was urging him to quit trucking entirely.',
    solution: 'Grow Trucking took over all dispatch, broker communication, and paperwork for Tommy. We matched him with a consistent freight lane hauling lumber products from Oregon mills to Midwest distribution centers — a lane with predictable timing that let Tommy reclaim his evenings. Our team manages all check calls, detention disputes, and invoice follow-ups.',
    routeOptimization: 'I-84 East to I-15 North to I-90 East. Identified a seasonal routing adjustment in winter that avoids the Lookout Pass closure risk, rerouting via I-84/US-93 with only a 31-mile addition but eliminating a historically costly weather delay.',
    metrics: [
      { label: 'Hours on Admin/Night', before: '3–4 hours', after: '0 hours' },
      { label: 'Near-Miss Safety Events', before: '2 in past quarter', after: '0 in 8 months' },
      { label: 'Revenue Change', before: '$5,100/week', after: '$5,850/week' },
      { label: 'Marriage/Family Stress', before: 'Considering quitting', after: 'Re-energized in career' },
    ],
  },
  {
    id: '9',
    slug: 'brenda-simmons',
    driverName: 'Brenda Simmons',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van',
    revenueIncrease: '$4,600/week',
    revenueIncreaseValue: 4600,
    rpmBefore: '$2.00',
    rpmAfter: '$2.85',
    freightLane: 'Automotive Parts / Retail / Beverage',
    region: 'Southeast',
    outcome: 'Revenue Increase',
    summary: 'Emergency contract loss recovery — loaded within 6 hours',
    challenge: 'Brenda was a dedicated carrier for a single retail shipper who abruptly cancelled her contract during a demand slowdown. With no backup brokers and a lease payment due in 10 days, she was in financial crisis. She called Grow Trucking with a single request: get me loads now.',
    solution: 'Within 6 hours of onboarding, Grow Trucking had Brenda loaded with a backhaul automotive parts run from Charlotte to Nashville. Over the following two weeks, we rebuilt her entire book of business with four new broker relationships across retail goods, beverage distribution, and medical supplies — providing lane diversity so she would never again rely on a single shipper.',
    routeOptimization: 'I-85 West to I-26 to I-40 West. Grow Trucking arranged a fuel discount through our fleet fuel program at 8 stops on this corridor, saving Brenda $0.14/gallon — meaningful on a lane she now runs 3x per week.',
    metrics: [
      { label: 'Time to First Load', before: 'In crisis, 0 loads', after: '6 hours after onboarding' },
      { label: 'Shipper Dependency', before: '100% one client', after: '4 active broker relationships' },
      { label: 'Weekly Revenue', before: '$0 (contract lost)', after: '$4,600/week' },
      { label: 'Fuel Savings/Year', before: 'No program', after: '$2,900/year' },
    ],
  },
  {
    id: '10',
    slug: 'roy-patterson',
    driverName: 'Roy Patterson',
    equipmentType: 'Tanker',
    equipmentBadge: 'Food-Grade Tanker (Liquid Bulk)',
    revenueIncrease: '+$904/week',
    revenueIncreaseValue: 904,
    rpmBefore: '$2.10',
    rpmAfter: '$2.95',
    freightLane: 'Specialty Liquid / Food-Grade / Industrial',
    region: 'Midwest',
    outcome: 'Revenue Increase',
    summary: 'Specialty liquid tanker repositioned to premium food-grade market',
    challenge: 'Roy drove a tanker and had specialty liquid bulk experience but was being dispatched on general freight tanker runs at commodity rates. His skills in food-grade and chemical tanker operation were entirely underutilized. Additionally, Roy struggled with appointment scheduling and had accumulated $4,200 in detention charges that brokers refused to pay.',
    solution: 'Grow Trucking repositioned Roy in the specialty liquid market — food-grade corn syrup and industrial lubricants between Midwest processing plants and Ohio manufacturers. We also pursued and successfully collected $3,100 of Roy\'s outstanding detention through our broker dispute escalation process. Going forward, all Roy\'s loads include Grow Trucking-enforced detention clauses.',
    routeOptimization: 'I-94 East to I-90 East. Identified a weight-optimized routing through Wisconsin that uses state-designated heavy haul corridors, avoiding permit requirements that had been adding $300 per trip unnecessarily.',
    metrics: [
      { label: 'Load Type', before: 'General tanker ($2.10/mi)', after: 'Specialty liquid ($2.95/mi)' },
      { label: 'Detention Recovered', before: '$0 collected', after: '$3,100 recovered' },
      { label: 'Permit Costs', before: '$300/trip', after: '$0 (rerouted)' },
      { label: 'Weekly Revenue Lift', before: 'Baseline', after: '+$904/week' },
    ],
  },
  {
    id: '11',
    slug: 'sandra-kevin-marsh',
    driverName: 'Sandra & Kevin Marsh',
    equipmentType: 'Dry Van',
    equipmentBadge: 'Kenworth T680 — 53\' Dry Van (Team)',
    revenueIncrease: '+$1,800/week',
    revenueIncreaseValue: 1800,
    rpmBefore: '$2.00',
    rpmAfter: '$2.58',
    freightLane: 'General Freight / Cross-Country Relay',
    region: 'West Coast',
    outcome: 'Home Time',
    summary: 'Team drivers redesigned to relay model with consistent home time',
    challenge: 'Sandra and Kevin were a married team-driving couple who were earning well on cross-country runs but burning out from coast-to-coast hauls with no home time. Their relationship was strained by the constant pressure. Kevin had developed a health condition requiring regular medical appointments, making the non-stop model unsustainable.',
    solution: 'Grow Trucking redesigned their operations around a relay model — running the LA-to-Denver leg on one cycle and the Denver-to-NY leg on another, with a 48-hour home base in Denver (where they lived) between legs. This created a hub-and-spoke structure that maintained their high team earnings while giving them consistent home time and medical appointment windows.',
    routeOptimization: 'I-15 North to I-70 East (LA-Denver), then I-70 East to I-76 to I-80 East (Denver-NY). Splitting at Denver also allowed each leg to be optimized for different shippers, improving rate quality on both segments.',
    metrics: [
      { label: 'Home Time/Month', before: '2 days', after: '8–10 days' },
      { label: 'Revenue vs. Before', before: '$3,100/week', after: '$4,900/week' },
      { label: 'Health Appointment Access', before: 'Severely limited', after: 'Reliable bi-weekly' },
      { label: 'Driver Reported Wellbeing', before: 'Burnout, strain', after: 'Sustainable long-term' },
    ],
  },
  {
    id: '12',
    slug: 'darnell-brooks',
    driverName: 'Darnell Brooks',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van (2 yrs experience)',
    revenueIncrease: '+$2,300/week',
    revenueIncreaseValue: 2300,
    rpmBefore: '$1.90',
    rpmAfter: '$2.72',
    freightLane: 'E-Commerce / General Freight',
    region: 'Southeast',
    outcome: 'Revenue Increase',
    summary: 'New driver mentorship program broke broker access barriers',
    challenge: 'Darnell was a newer driver (2 years experience) who couldn\'t break into lanes dominated by preferred carriers with years of broker relationships. He was stuck on load boards with terrible rates and had been turned down by 7 brokers in a row due to his limited load history. He felt the industry was designed to keep new drivers at the bottom.',
    solution: 'Grow Trucking provides new driver mentorship as part of our dispatch service. We enrolled Darnell in our Carrier Development Program, co-signed his first three broker applications with our Grow Trucking carrier reputation, and placed him on a supervised lane learning track with e-commerce freight on the Atlanta-DC corridor — a lane with high load frequency and broker relationships we already held.',
    routeOptimization: 'I-85 North to I-95 North. Grow Trucking mapped all weigh station locations, scale bypass eligibility, and provided Darnell with a detailed compliance briefing for Virginia DOT requirements, which had tripped him up on a previous run.',
    metrics: [
      { label: 'Broker Applications Approved', before: '0 of 7 (rejected)', after: '3 of 3 (with Grow Trucking)' },
      { label: 'Rate per Mile', before: '$1.90/mile', after: '$2.72/mile' },
      { label: 'Load Board Dependency', before: '100% load board', after: '30% (70% contracted)' },
      { label: 'Month 6 Weekly Revenue', before: '$1,600', after: '$3,900' },
    ],
  },
  {
    id: '13',
    slug: 'patricia-hendricks',
    driverName: 'Patricia "Pat" Hendricks',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van',
    revenueIncrease: '+$2,500/week',
    revenueIncreaseValue: 2500,
    rpmBefore: '$2.05',
    rpmAfter: '$2.78',
    freightLane: 'General Freight / Retail Distribution',
    region: 'Midwest',
    outcome: 'Revenue Increase',
    summary: 'Invoicing and collections overhaul recovered $17,500 in receivables',
    challenge: 'Pat had been an excellent driver for 15 years but was terrible at invoicing. She frequently forgot to submit proof of delivery, sent invoices to wrong contacts, and had outstanding receivables of $22,000 — some going back 5 months. She was cash-poor despite doing strong volume. Her bank had denied a truck maintenance loan due to inconsistent cash flow records.',
    solution: 'Grow Trucking took over Pat\'s invoicing, collections, and financial documentation. We traced and recovered $17,500 of her outstanding $22,000 in receivables within 45 days. Our team implemented QuickBooks integration with same-day POD upload, and within 90 days Pat had a clean 90-day revenue record that allowed her to successfully refinance her truck at a better rate.',
    routeOptimization: 'I-35 North to I-44 to I-55 North. Identified a fuel optimization circuit using Pat\'s existing fuel card at Casey\'s locations, reducing her fuel spend by $190 per round trip.',
    metrics: [
      { label: 'Receivables Recovered', before: '$22,000 outstanding', after: '$17,500 recovered (45 days)' },
      { label: 'Invoice Submission Speed', before: '3–7 days (often forgotten)', after: 'Same-day (automated)' },
      { label: 'Fuel Cost per Round Trip', before: '$1,080', after: '$890' },
      { label: 'Loan Application', before: 'Denied', after: 'Approved after 90 days' },
    ],
  },
  {
    id: '14',
    slug: 'marco-santini',
    driverName: 'Marco Santini',
    equipmentType: 'Reefer',
    equipmentBadge: '53\' Refrigerated Trailer',
    revenueIncrease: '+$4,500/week',
    revenueIncreaseValue: 4500,
    rpmBefore: '$2.10',
    rpmAfter: '$2.88',
    freightLane: 'Produce / Gulf Seafood / Specialty Food',
    region: 'Southeast',
    outcome: 'Revenue Increase',
    summary: 'Triangulated route eliminated 60% empty miles on southbound leg',
    challenge: 'Marco hauled refrigerated produce from South Florida to Gulf Coast markets but had been caught in a cycle where southbound backhauls were nearly impossible to find, leaving him empty 60% of the time heading south from New Orleans. His operating ratio was over 95%, meaning he was barely covering costs. He had tried 4 dispatch services before Grow Trucking.',
    solution: 'Grow Trucking discovered that Mardi Gras season and Gulf seafood processing had strong northbound freight that few dispatchers knew how to tap. We connected Marco with three Gulf Coast seafood exporters and a specialty food manufacturer running Miami-bound loads. By triangulating his route through Baton Rouge, we added a profitable third leg to what had been a two-leg trip.',
    routeOptimization: 'I-95 South to US-41 to I-10 West (Miami to New Orleans), then US-90 to Baton Rouge for seafood pickup, then I-10/I-12 back to I-95 North. The triangulated route added 80 miles but generated an additional $900 in revenue per cycle.',
    metrics: [
      { label: 'Empty Mile Rate', before: '60% empty southbound', after: '12% empty (triangulated)' },
      { label: 'Operating Ratio', before: '95.4%', after: '78.2%' },
      { label: 'Revenue per Cycle', before: '$2,100', after: '$4,350' },
      { label: 'Previous Dispatchers', before: '4 failed attempts', after: 'Grow Trucking — problem solved' },
    ],
  },
  {
    id: '15',
    slug: 'victor-osei',
    driverName: 'Victor Osei',
    equipmentType: 'Dry Van',
    equipmentBadge: '53\' Dry Van',
    revenueIncrease: '+$2,300/week',
    revenueIncreaseValue: 2300,
    rpmBefore: '$1.95',
    rpmAfter: '$2.62',
    freightLane: 'General Freight / Consumer Goods',
    region: 'West Coast',
    outcome: 'Revenue Increase',
    summary: 'Language barriers removed, unfair lease terms renegotiated',
    challenge: 'Victor was an immigrant driver who had recently obtained his CDL and faced language and cultural barriers in broker negotiations. He was consistently underpaid, often talked into lower rates by aggressive brokers, and had signed unfavorable lease terms he didn\'t fully understand. He came to Grow Trucking after a broker refused to pay for a load, claiming paperwork issues.',
    solution: 'Grow Trucking immediately took over all broker communications on Victor\'s behalf, removing the negotiation burden entirely. We reviewed his lease agreement and connected him with a transportation attorney who renegotiated two unfair clauses. Grow Trucking also recovered the unpaid load ($1,840) by filing a proper claims dispute and enrolled Victor in our carrier financial literacy workshop.',
    routeOptimization: 'I-70 West to I-15 South to I-80 West to I-580. Identified that Victor had been taking I-50 through Nevada adding 44 miles unnecessarily. Route correction alone saves $62 per trip in fuel.',
    metrics: [
      { label: 'Unpaid Load Recovered', before: '$1,840 withheld', after: '$1,840 recovered' },
      { label: 'Rate per Mile', before: '$1.95/mile (negotiated down)', after: '$2.62/mile (Grow Trucking rate)' },
      { label: 'Lease Terms', before: '2 unfair clauses', after: 'Renegotiated by attorney' },
      { label: 'Route Fuel Waste/Year', before: '$3,720 excess', after: 'Eliminated' },
    ],
  },
]

// Helper functions
export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
  return caseStudies.find(cs => cs.slug === slug)
}

export function getAllCaseStudies(): CaseStudy[] {
  return caseStudies
}

export function getFeaturedCaseStudies(): CaseStudy[] {
  return caseStudies.filter(cs => cs.featured)
}
